### ISSUE TITLE
Add support for limitations on texts

### ISSUE THREAD

**Issue by Nashor** [TapestryMinecraft/at-chat-sms#1]
There should be a way to limit who can send texts and how many texts players are allowed to send in a certain period of time. Perhaps add support for:
- A whitelist
- A blacklist
- Specifying message limits for individuals or groups

**Comment by ItsNickBarry** [comment]
I think these features might be outside of the scope of the plugin.  The 75-SMS limit is too low for large servers, and small servers don't need these features.

If there's any demand, we could release a more robust SMS plugin for larger servers, but they would have to register for a paid SMS service if they want higher limits.
